global:
  scrape_interval: 30s
  external_labels:
    monitor: 'my-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'amp'
    metrics_path: '/amp/metrics'
    params:
      sap-client: [001]
      scenario: [example-prom]
    basic_auth:
      username: 'DEVELOPER'
      password: 'Down1oad'
    static_configs:
      - targets: ['vhcalnplci:8000']
