name: Run abaplint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  abaplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: abaplint
      uses: abaplint/actions-abaplint@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
